language: node_js
node_js:
- 8
- 10
cache:
  directories:
    - node_modules
branches:
  only:
    - master
    - /^greenkeeper/.*$/
notifications:
  email: false
before_install:
  - "npm i -g npm@latest"
install:
  - npm install
before_script:
  - npm prune
deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release
