language: node_js
node_js: 10
cache:
  directories:
    - node_modules
branches:
  only:
    - master
    - /^greenkeeper/.*$/
notifications:
  email: false
before_install:
  - "npm i -g npm@latest"  
install:
  - npm install
  - npm i @octokit/request-error
before_script:
  - npm prune
deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release
